---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myhostzo/public_html/supid.myhostzone.biz.id
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp -R api $DEPLOYPATH/
    - /bin/cp database.sql $DEPLOYPATH/
